CREATE TABLE IF NOT EXISTS question_packages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  status ENUM('draft', 'published') NOT NULL DEFAULT 'draft',
  is_archived TINYINT(1) NOT NULL DEFAULT 0,
  is_invalid TINYINT(1) NOT NULL DEFAULT 0,
  invalid_reason VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
